version: '2'
services:
    nginx:
        image: nginx:latest
        container_name: ng01
        ports:
            - "8000:8000"
        volumes:
            - ./src:/src
            - ./deploy/nginx:/etc/nginx/conf.d
            - /static:/static
        depends_on:
            - web
    web:
        build: .
        container_name: dg01
        command: bash -c "sleep 8 && python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && uwsgi --ini /usr/local/etc/toniksql.ini"
        depends_on:
            - db
        volumes:
            - ./src:/src
            - ./deploy/uwsgi:/usr/local/etc/
            - /static:/static
        expose:
            - "8000"
    db:
        image: postgres:latest
        container_name: ps01
