# Generated by Django 2.0.1 on 2018-02-16 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_auto_20180216_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_tables', to='tasks.Task_db')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_tables', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
