# Generated by Django 2.0.1 on 2018-02-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20180216_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_db',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task_table',
            name='description',
            field=models.TextField(default='--'),
        ),
        migrations.AlterField(
            model_name='task_db',
            name='dbname',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='task_db',
            name='staffname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task_table',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='task_table',
            name='staffname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
