# Generated by Django 2.0.1 on 2018-02-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20180216_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribes',
            name='is_passed',
            field=models.BooleanField(default=False),
        ),
    ]
