# Generated by Django 2.0.1 on 2018-02-17 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_subscribes_is_passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='tasks.Task'),
        ),
    ]
