# Generated by Django 2.0.1 on 2018-02-16 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_subscribes'),
        ('einvite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='invites', to='tasks.Course'),
            preserve_default=False,
        ),
    ]
